CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    account_type VARCHAR(20),
    date_of_birth DATE,
    gender VARCHAR(20),
    address VARCHAR(255),
    profile_image_path VARCHAR(255),
    license_number VARCHAR(50),
    license_expiry_date DATE,
    license_document_path VARCHAR(255),
    id_document_path VARCHAR(255),
    vehicle_plate VARCHAR(20),
    vehicle_model VARCHAR(100),
    vehicle_year INT,
    vehicle_color VARCHAR(30),
    company_registration_path VARCHAR(255),
    company_registration_no VARCHAR(50),
    company_name VARCHAR(100),
    company_email VARCHAR(100),
    company_phone VARCHAR(20),
    company_location VARCHAR(255),
    company_description VARCHAR(1000),
    email_verified BIT(1) DEFAULT b'1',
    enabled BIT(1) DEFAULT b'1',
    account_locked BIT(1) DEFAULT b'0',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    last_login_at DATETIME NULL,
    password_changed_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email),
    KEY idx_user_role (role),
    KEY idx_user_account_type (account_type),
    KEY idx_user_enabled (enabled)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS companies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NULL,
    company_name VARCHAR(150) NOT NULL,
    company_email VARCHAR(100) NULL,
    company_phone VARCHAR(20) NULL,
    registration_number VARCHAR(50) NULL,
    tax_id VARCHAR(50) NULL,
    address VARCHAR(255) NULL,
    city VARCHAR(100) NULL,
    region VARCHAR(100) NULL,
    postal_code VARCHAR(20) NULL,
    description VARCHAR(1000) NULL,
    logo_path VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL,
    verified_at DATETIME NULL,
    verification_notes VARCHAR(500) NULL,
    wallet_balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    commission_rate DECIMAL(5,2) NOT NULL DEFAULT 10.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_companies_user (user_id),
    UNIQUE KEY uk_companies_name (company_name),
    UNIQUE KEY uk_companies_email (company_email),
    UNIQUE KEY uk_companies_registration (registration_number),
    KEY idx_company_status (status),
    CONSTRAINT fk_companies_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS cars (
    id BIGINT NOT NULL AUTO_INCREMENT,
    driver_id BIGINT NULL,
    company_id BIGINT NULL,
    plate_number VARCHAR(20) NOT NULL,
    car_brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    `year` INT NULL,
    color VARCHAR(30) NULL,
    total_seats INT NOT NULL DEFAULT 18,
    vin VARCHAR(50) NULL,
    chassis_number VARCHAR(50) NULL,
    engine_number VARCHAR(50) NULL,
    status VARCHAR(20) NOT NULL,
    roadworthy_expiry DATETIME NULL,
    insurance_expiry DATETIME NULL,
    last_inspection_date DATETIME NULL,
    image_path VARCHAR(255) NULL,
    description VARCHAR(500) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cars_plate (plate_number),
    KEY idx_car_driver (driver_id),
    KEY idx_car_company (company_id),
    KEY idx_car_status (status),
    CONSTRAINT fk_cars_driver FOREIGN KEY (driver_id) REFERENCES users (id),
    CONSTRAINT fk_cars_company FOREIGN KEY (company_id) REFERENCES companies (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS trips (
    id BIGINT NOT NULL AUTO_INCREMENT,
    car_id BIGINT NOT NULL,
    driver_id BIGINT NULL,
    company_id BIGINT NULL,
    from_location VARCHAR(100) NOT NULL,
    to_location VARCHAR(100) NOT NULL,
    pickup_station VARCHAR(150) NULL,
    drop_off_station VARCHAR(150) NULL,
    departure_time DATETIME NOT NULL,
    arrival_time DATETIME NULL,
    trip_amount DECIMAL(10,2) NOT NULL,
    available_seats INT NOT NULL,
    total_seats INT NOT NULL,
    description VARCHAR(500) NULL,
    status VARCHAR(50) NOT NULL,
    cancel_reason VARCHAR(100) NULL,
    cancel_reason_details VARCHAR(500) NULL,
    cancelled_by BIGINT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    expired_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_trip_status (status),
    KEY idx_trip_departure (departure_time),
    KEY idx_trip_driver (driver_id),
    KEY idx_trip_company (company_id),
    KEY idx_trip_car (car_id),
    KEY idx_trip_from_to (from_location, to_location),
    CONSTRAINT fk_trips_car FOREIGN KEY (car_id) REFERENCES cars (id),
    CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES users (id),
    CONSTRAINT fk_trips_company FOREIGN KEY (company_id) REFERENCES companies (id),
    CONSTRAINT fk_trips_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    loyalty_points DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(3) NOT NULL DEFAULT 'GHS',
    is_active BIT(1) DEFAULT b'1',
    last_transaction_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wallets_user (user_id),
    KEY idx_wallet_currency (currency),
    CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS seat_maps (
    id BIGINT NOT NULL AUTO_INCREMENT,
    trip_id BIGINT NOT NULL,
    car_id BIGINT NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    `row_number` INT NULL,
    column_label VARCHAR(5) NULL,
    seat_type VARCHAR(20) NOT NULL,
    extra_legroom BIT(1) DEFAULT b'0',
    status VARCHAR(20) NOT NULL,
    held_by_booking_id BIGINT NULL,
    hold_expires_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_seat_maps_trip_seat (trip_id, seat_number),
    KEY idx_seatmap_status (status),
    KEY idx_seatmap_car (car_id),
    CONSTRAINT fk_seat_maps_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_seat_maps_car FOREIGN KEY (car_id) REFERENCES cars (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    seat_map_id BIGINT NULL,
    booking_reference VARCHAR(20) NOT NULL,
    seat_number INT NULL,
    booking_date DATETIME NOT NULL,
    updated_at DATETIME NULL,
    status VARCHAR(50) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    booking_type VARCHAR(50) NOT NULL,
    passenger_name VARCHAR(100) NULL,
    passenger_phone VARCHAR(20) NULL,
    payment_method VARCHAR(50) NULL,
    payment_status VARCHAR(50) NOT NULL,
    transaction_reference VARCHAR(100) NULL,
    payment_date DATETIME NULL,
    cancel_reason VARCHAR(100) NULL,
    cancel_reason_details VARCHAR(500) NULL,
    cancelled_by BIGINT NULL,
    cancelled_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_bookings_reference (booking_reference),
    KEY idx_booking_user (user_id),
    KEY idx_booking_trip (trip_id),
    KEY idx_booking_status (status),
    KEY idx_booking_payment_status (payment_status),
    KEY idx_booking_date (booking_date),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
    CONSTRAINT fk_bookings_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id)
) ENGINE=InnoDB;

ALTER TABLE seat_maps
    ADD CONSTRAINT fk_seat_maps_held_by_booking FOREIGN KEY (held_by_booking_id) REFERENCES bookings (id);

ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_seat_map FOREIGN KEY (seat_map_id) REFERENCES seat_maps (id);

CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT NOT NULL AUTO_INCREMENT,
    booking_id BIGINT NULL,
    rating INT NOT NULL,
    comment VARCHAR(500) NULL,
    passenger_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    trip_id BIGINT NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_reviews_booking (booking_id),
    KEY idx_reviews_driver (driver_id),
    KEY idx_reviews_passenger (passenger_id),
    KEY idx_reviews_trip (trip_id),
    CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT fk_reviews_passenger FOREIGN KEY (passenger_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_driver FOREIGN KEY (driver_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wallet_transactions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    wallet_id BIGINT NULL,
    booking_id BIGINT NULL,
    type VARCHAR(20) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    balance_after DECIMAL(15,2) NOT NULL,
    loyalty_balance_after DECIMAL(15,2) NULL,
    reference VARCHAR(100) NOT NULL,
    provider VARCHAR(50) NULL,
    provider_ref VARCHAR(100) NULL,
    description VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL,
    metadata TEXT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_wallet_transactions_booking (booking_id),
    KEY idx_wtx_user (user_id),
    KEY idx_wtx_type (type),
    KEY idx_wtx_status (status),
    KEY idx_wtx_reference (reference),
    KEY idx_wtx_provider_ref (provider_ref),
    CONSTRAINT fk_wallet_transactions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_wallet_transactions_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id),
    CONSTRAINT fk_wallet_transactions_booking FOREIGN KEY (booking_id) REFERENCES bookings (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    action_url VARCHAR(500) NULL,
    `read` BIT(1) DEFAULT b'0',
    read_at DATETIME NULL,
    priority VARCHAR(20) DEFAULT 'NORMAL',
    metadata TEXT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_notif_user (user_id),
    KEY idx_notif_type (type),
    KEY idx_notif_read (`read`),
    KEY idx_notif_created (created_at),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS coupons (
    code VARCHAR(32) NOT NULL,
    title VARCHAR(120) NOT NULL,
    discount_type VARCHAR(20) NOT NULL,
    discount_value DECIMAL(10,2) NOT NULL,
    max_discount DECIMAL(10,2) NULL,
    min_order_amount DECIMAL(10,2) NULL,
    max_uses INT NULL DEFAULT 1000,
    used_count INT NULL DEFAULT 0,
    first_ride_only BIT(1) DEFAULT b'0',
    active BIT(1) DEFAULT b'1',
    starts_at DATETIME NULL,
    expires_at DATETIME NULL,
    created_at DATETIME NULL,
    PRIMARY KEY (code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    token VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    expiry_date DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_password_reset_token (token),
    KEY idx_prt_user (user_id),
    KEY idx_prt_expiry (expiry_date),
    CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT NOT NULL AUTO_INCREMENT,
    token VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at DATETIME NOT NULL,
    verified BIT(1) NOT NULL DEFAULT b'0',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_verification_tokens_token (token),
    UNIQUE KEY uk_verification_tokens_user (user_id),
    KEY idx_vt_expires (expires_at),
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS login_attempts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_attempt DATETIME NULL,
    locked_until DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_login_attempts_username (username)
) ENGINE=InnoDB;
